name: 'Generate snake animation'

on:
  # Trigger the workflow on pushes to the main branch and at 4 AM UTC every day
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  Generate-SVG:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate the SVG using the Platane/snk action
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}

      # Commit and push the generated SVG back to the repository
      - name: Commit and push SVG
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add -A
          git commit -m "Generated snake animation"
          git push
